### ISSUE TITLE
[Discussion] Gets stuck at creating api. 

### ISSUE THREAD

**Issue by StapleBacon5037** [SpotifyXP/SpotifyXP#31]
Around 1/10 times it manages to get past. On the latest nightly right now
[Debug Log.txt](https://github.com/SpotifyXP/SpotifyXP/files/14932574/Debug.Log.txt)
There's the log from the other 9/10 times it failed.

**Comment by werwolf2303** [comment]
Do you have Spotify Premium?

**Comment by StapleBacon5037** [comment]
No

**Comment by StapleBacon5037** [comment]
I think I've gotten it to work. It was just an issue when I updated Spotifyxp, it didn't replace the original shortcut in my start menu. However I'm running into this issue whenever I try playing a song``
![tmp_105702cd-d2d9-49c8-a786-df776085f3e6](https://github.com/SpotifyXP/SpotifyXP/assets/76448863/0c536cca-adbe-4536-bddb-f0114d27f370)
I'll send the log in a second. I can't play songs at all I should clarify

**Comment by StapleBacon5037** [comment]
OK, nevermind, I didn't fix that previous issue. It worked twice after doing it but now it won't open again

**Comment by werwolf2303** [comment]
librespot-java requires Spotify Premium to work and the Spotify Web API too. I'm surprised that SpotifyXP even starts. (Sorry if this sounds rude) Why do you use Spotify without paying for premium?

**Comment by StapleBacon5037** [comment]
Because I'm poor

**Comment by StapleBacon5037** [comment]
It was working fine in the past, in fact it's only after this latest update that I wasn't able to play anything. No, there weren't ads. It's almost like you got me premium for free

**Comment by StapleBacon5037** [comment]
[Debug Log 1.txt](https://github.com/SpotifyXP/SpotifyXP/files/14957120/Debug.Log.1.txt)
[Debug Log 2.txt](https://github.com/SpotifyXP/SpotifyXP/files/14957122/Debug.Log.2.txt)
These are 2 of the logs. 1 after trying to play a song. It occasionally sends every few mins

**Comment by werwolf2303** [comment]
I have a premium idea for you: 

1. Apply for 3 months Spotify Premium test
2. Cancel the abo
3. When it expires do 1.

**Comment by StapleBacon5037** [comment]
I can't claim the 3 months because I do not have a card

**Comment by StapleBacon5037** [comment]
I'm going to go back and use your version from January and see if that works

**Comment by werwolf2303** [comment]
I will see what changed and try to revert that

**Comment by StapleBacon5037** [comment]
It doesn't seem to function anymore. I just get an immediate critical error

**Comment by werwolf2303** [comment]
Ok so Spotify changed something. How old are you? (You don't have to answer)

**Comment by StapleBacon5037** [comment]
It was working fine till I updated yesterday. I'll have to find the original version I installed

**Comment by werwolf2303** [comment]
18... same as me. Ok when you found it please give me a link to that jar file

**Comment by StapleBacon5037** [comment]
Unfortunately the oldest nightly that hasn't expired still doesn't work. How do I delete my user data, maybe that's the issue

**Comment by werwolf2303** [comment]
Under %AppData% is a folder named SpotifyXP, delete that

**Comment by StapleBacon5037** [comment]
Yeah, it doesn't work anymore. Spotify must've done something. I guess that's why you've been getting an influx of these errors as of recently

**Comment by werwolf2303** [comment]
Ok so I will close this issue as "can't/reproduce"

**Comment by werwolf2303** [comment]
OK weird but I can't implement fixes right now because I'm reworking the ui at the moment. (Spoiler: Resize feature)

**Comment by Jri-creator** [comment]
Maybe Spotify changed credential verification, and had to be updated in the Credentials.json

**Comment by werwolf2303** [comment]
Can be

**Comment by werwolf2303** [comment]
Can be

**Comment by Jri-creator** [comment]
If it is, maybe have it check to see if the current credentials work, and if not, make new ones.

If it's not, I don't know.

**Comment by werwolf2303** [comment]
If I'm honest: I don't know how long I can support SpotifyXP because the heart of SpotifyXP librespot-java is not being actively developed anymore so it can be that I have to end support tomorrow for a while

**Comment by Jri-creator** [comment]
I understand. Hopefully you find something that would work better for SpotifyXP, even if it means re-working the program to support it.

**Comment by Jri-creator** [comment]
I'm having a hard time learning reverse engineering. Good Luck!

**Comment by Jri-creator** [comment]
It has been a day since I reset [deleted and re-installed] SpotifyXP, and it still works.

Token refresh?

**Comment by werwolf2303** [comment]
Ok I will add that to my todo list

**Comment by Jri-creator** [comment]
Maybe let people know who has SpotifyXP & this issue occurring to delete all contents of SpotifyXP [the SpotifyXP folder, basically] and reinstall it. I don't know. 

Or, Re-run SpotifyXP w/o the --setup-complete extension to re-write the necessary credentials.

**Comment by werwolf2303** [comment]
Do you want to add the wiki and and entry for this?

**Comment by Jri-creator** [comment]
Not sure how to do this, but I can.

**Comment by Jri-creator** [comment]
I've got that added in. So, are we using the Wiki to post solutions to bugs or problems for the users of SpotifyXP to read?

**Comment by werwolf2303** [comment]
Yes

**Comment by Jri-creator** [comment]
Quick Update on "librespot-java requires Spotify Premium to work", it doesn't need Spotify Premium, it will function without. SpotifyXP doesn't play ads, and will still play songs, even without Spotify Premium.

**Comment by StapleBacon5037** [comment]
> Quick Update on "librespot-java requires Spotify Premium to work", it doesn't need Spotify Premium, it will function without. SpotifyXP doesn't play ads, and will still play songs, even without Spotify Premium.

Can confirm, I found a old version from janurary on my brothers pc that worked perfectly

**Comment by werwolf2303** [comment]
No, I only store the user configuratioin Config.json

**Comment by werwolf2303** [comment]
I can't reproduce this. On the macbook it works since day 1 I started developing SpotifyXP on it

**Comment by Jri-creator** [comment]
You may not be able to reproduce it due to the J.R.E. you are using. The Mac's J.R.E. may run a bit differently compared to Windows and [Ubuntu] Linux.

J.R.E. - Java Runtime Environment 

At least there is a working solution in the wiki?

**Comment by Jri-creator** [comment]
I used to have an old laptop that ran windows xp sp3 [uses intel atom] but it no longer works, not even on the charger. The closest old PC that I got is the one I'm currently using. [Acer C720 Chromebook, modified to run Ubuntu 23.10, uses Intel Celeron]

**Comment by Jri-creator** [comment]
SpotifyXP is still working, but with the [Panic State in PlayerListener] error occurring after 7 songs.

**Comment by Jri-creator** [comment]
SpotifyXP is still working, but with the [Panic State in PlayerListener] error occurring after 12 songs.

**Comment by Jri-creator** [comment]
I think I know why the [Panic State in PlayerListener] error occurs. For Spotify Free users, after a certain amount of songs, Spotify calls for an Ad, and SpotifyXP doesn't know what to do, thus, causing a Panic.

**Comment by werwolf2303** [comment]
Sounds possible. So I will implement a reconnect on panic

**Comment by Jri-creator** [comment]
On Spotify on Web, with an AdBlocker enabled, Spotify will stop working until you reload the player, because Spotify can't call for an Ad, causing a Panic in their Web player. That's what I think is the case for SpotifyXP, since it can't call for an Ad.

**Comment by werwolf2303** [comment]
@Jri-creator If you have a VPN can you try if Spotify free works with SpotifyXP because for me it doesn't. If you can do it please connect to a server in Germany

**Comment by Jri-creator** [comment]
Sorry, but I am unable to acquire/obtain a VPN connection to Germany. Spotify won't provide their services to users of a VPN [For some weird reason].

**Comment by Jri-creator** [comment]
Also, SpotifyXP can't acquire an API Connection, even after app reset, when I use a VPN.

**Comment by werwolf2303** [comment]
It's weird that it works for you because if I login with a free account it just skips every song and then eventually panic

**Comment by werwolf2303** [comment]
Please try the newest nightly build

**Comment by Jri-creator** [comment]
Very Sorry for the late response. The newest Nightly won't install, at all! 

Terminal Output:
` java -jar SpotifyXP.jar
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "javax.swing.JLabel.setText(String)" because "this.linfo" is null
	at com.spotifyxp.panels.SplashPanel.show(SplashPanel.java:21)
	at com.spotifyxp.Initiator.initSplashPanel(Initiator.java:109)
	at com.spotifyxp.Initiator.main(Initiator.java:67)
`

**Comment by StapleBacon5037** [comment]
> Very Sorry for the late response. The newest Nightly won't install, at all!
> 
> Terminal Output: `java -jar SpotifyXP.jar Exception in thread "main" java.lang.NullPointerException: Cannot invoke "javax.swing.JLabel.setText(String)" because "this.linfo" is null at com.spotifyxp.panels.SplashPanel.show(SplashPanel.java:21) at com.spotifyxp.Initiator.initSplashPanel(Initiator.java:109) at com.spotifyxp.Initiator.main(Initiator.java:67)`

![image](https://github.com/SpotifyXP/SpotifyXP/assets/76448863/26bdfcb4-8a3e-4d37-ab3f-540dc8773cb6)
same

**Comment by Jri-creator** [comment]
> > Very Sorry for the late response. The newest Nightly won't install, at all!
> > Terminal Output: `java -jar SpotifyXP.jar Exception in thread "main" java.lang.NullPointerException: Cannot invoke "javax.swing.JLabel.setText(String)" because "this.linfo" is null at com.spotifyxp.panels.SplashPanel.show(SplashPanel.java:21) at com.spotifyxp.Initiator.initSplashPanel(Initiator.java:109) at com.spotifyxp.Initiator.main(Initiator.java:67)`
> 
> ![image](https://private-user-images.githubusercontent.com/76448863/338188549-26bdfcb4-8a3e-4d37-ab3f-540dc8773cb6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwNDQ4MDcsIm5iZiI6MTcxODA0NDUwNywicGF0aCI6Ii83NjQ0ODg2My8zMzgxODg1NDktMjZiZGZjYjQtOGEzZS00ZDM3LWFiM2YtNTQwZGM4NzczY2I2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEwVDE4MzUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0Yzk1ZjVkZWI4OTg4MzNiOWE1MmM5ZDM1Nzk4OWEzNDkwYmZlMDMzYWUzODkxOWY3YjljYTJkNzdhMzczNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PwA86e_3hmByJgOV4rWGhyRTMRC7qMeP5-FYpZnxl1Y) same

So it's not just New Java users.

**Comment by Jri-creator** [comment]
For an unknown reason, I can't edit the SpotifyXP wiki. What do I have to do in order to edit the SpotifyXP Wiki to include the new solution(s) to problem(s)?

**Comment by werwolf2303** [comment]
!!!This project is DEAD!!! For updates: https://github.com/SpotifyXP/SpotifyXP/issues/51. I will leave the repository open for someone to fix it
