### ISSUE TITLE
Can't install SpotifyXP

### ISSUE THREAD

**Issue by tibidegamebaas** [SpotifyXP/SpotifyXP#67]
Hi, I am running Windows XP SP2 in Dutch. (see screenshot)
![naamloos](https://github.com/user-attachments/assets/a3da46e7-8979-40f2-88ed-9d2fba32214a)
JAVA_HOME is correctly configured in environment variables, and Python, Java & Maven are in PATH.
I was able to init and build SpotifyXP.jar but when I execute `java -jar SpotifyXP.jar` I get:
```
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/spotifyxp/Initiator : Unsupported major.minor version 52.0
at java.lang.ClassLoader.defineClass1(Native Method)
at java.lang.ClassLoader.defineClass(Unknown Source)
at java.security.SecureClassLoader.defineClass(Unknown Source)
at java.net.URLClassLoader.defineClass(Unknown_Source)
at java.net.URLClassLoader.access$100(Unknown Source)
at java.net.URLClassLoader$1.run(Unknown Source)
at java.net.URLClassLoaderş1.run(Unknown Source)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)
at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown_Source)
at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
```
I eventually found the precompiled .jar file, but that gave me the same error. When I run it on my Windows 11 laptop, the installer opens.
I have installed Java 7, Python 3.4.4 and Apache Maven 3.9.9.
Do I need to upgrade to SP3 or what should I do?

**Comment by tibidegamebaas** [comment]
Nevermind, I figured out how to install Java 8 (I had to use the .msi installer, the .exe installer doesn't work).

**Comment by werwolf2303** [comment]
I want to support Java 7 some time in the future but that wouldn't need a big rewrite
